## YAML Template.
---
plugins:
  ## --------------------------------------------------------------------------
  ##  Links plugin
  ## ----------------------------
  ##  Links to friends, stuff
  ## --------------------------------------------------------------------------
  ##
  Links:
    parts:
      ## The list
      Links:
      ## Link categories
      LinkCategories: