##
## File to use with superBake 0.3
##
## @copyright     Copyright 2012, Manuel Tancoigne (http://experimentslabs.com)
## @author        Manuel Tancoigne <m.tancoigne@gmail.com>
## @link          http://experimentslabs.com Experiments Labs
## @package       ELCMS.superBake.Templates.Default
## @license       GPL v3 (http://www.gnu.org/licenses/gpl.html)
## @version       0.3
##
##-----------------------------------------------------------------------
##
## Configuration file for ExperimentsLabs
## -------------------------
##      Configuration for a "blog" plugin
##
## ----------------------------
##  Contains: Posts, PostCategories
## --------------------------------------------------------------------------
## <Other notes goes here>
##
##-----------------------------------------------------------------------
---
plugins:
  Blog:
    parts:
      ## Posts
      Posts:
        controller:
          actions:
            public:
              view:
                options:
                  conditions:
                    Post.published: 1
                view:
                  options:

              index:
                options:
                  conditions:
                    Post.published: 1
                    Post.publication_date <=: %now%
                view:
                  template: index
            admin:
            
        options:
          fieldNames:
            user_id: Author
      ## Post categories
      PostCategories:
        options:
          fieldNames:
            user_id: Author